### ISSUE TITLE
VestaCP support recent release Debian 9 ?

### ISSUE THREAD

**Issue by blackyzero** [serghey-rodin/vesta#1216] opened 2017-06-19 10:59 UTC
Hi all,

Would VestaCP work on latest release of Debian 9?
Thank you.

**Comment by Skamasle** [comment] 2017-06-19 21:33
Not supported yet officially

**Comment by blackyzero** [comment] 2017-06-20 11:02
Do you have plan to release support version for it?

**Comment by bsbudhwar** [comment] 2017-06-22 08:17
My is running on Debian 9 i updated the Debian 8 to 9

**Comment by konne** [comment] 2017-06-22 09:46
>Not supported yet officially
is there a way to install it unofficially, because the installer blocks it

**Comment by skurudo** [comment] 2017-06-22 10:32
Mask release name in /etc/issue
Change from "Debian GNU/Linux 9 \n \l" to Debian GNU/Linux 8 \n \l

**Comment by konne** [comment] 2017-06-22 16:38
@skurudo this is not work, it still complains. I looked into the vst-install-debian.sh and this is taking uname -a and /etc/debian_version
Did you tested you idea?

Any other better ideas?

**Comment by skurudo** [comment] 2017-06-23 06:59
@konne it was method for Debian 8 and debain/ubuntu family OS like Kubuntu

**Comment by skurudo** [comment] 2017-06-23 07:00
I think, installer needs more modifications for Debian 9 ;-(

**Comment by dpeca** [comment] 2017-06-23 08:36
Does anybody from VestaCP team received my email from May 11, with subject "Debian 9 is comming..." where I asked dev team for ''diff of Debian8 original vs Vesta config files'' so I can apply it on Debian9 config files, and I also asked there if dev team agree that I should try to adapt installer for Debian9? :)

**Comment by anton-reutov** [comment] 2017-06-23 16:01
@dpeca, you can try :)
I will read your message.

**Comment by dpeca** [comment] 2017-06-23 16:16
I want to try, but I need diff of Debian8 original conf files vs Vesta config files for Debian8, so I can see what you added to Debian8 conf files so I can add it to Debian9 config files too :)

**Comment by n1trux** [comment] 2017-06-26 05:47
@skurudo 

>Mask release name in /etc/issue

**THIS IS NOT A GOOD IDEA, DO NOT DO THIS!**

It will break other apps which rely on checking the `/etc/issue` file. Don't ever modify system files unless you know exactly what you're doing!

Rather change vesta installer files instead.

@dpeca why don't you download the source from this repository and do the diff yourself? Most of the stuff you need is here: https://github.com/serghey-rodin/vesta/tree/master/install/debian/8

You should make yourself familiar with how the installer does things before modifying stuff anyway. I suggest setting up a VM or LXC container with Debian and working with VM/btrfs snapshots.

**Comment by dpeca** [comment] 2017-06-26 07:24
@n1trux 
hmmm, it's good idea, just I need to found Debian8.0 image installation - and I mean exactly 8.0 - not latest 8.8 - because I guess someone who 'adapted' config files did it on base of 8.0 config files.
But neither we can not be sure about that... maybe that person modified 8.1, 8.2...

@serghey-rodin @anton-reutov @skurudo maybe someone of you have that information?

**Comment by ivmm** [comment] 2017-06-26 08:03
@dpeca 

https://cdimage.debian.org/mirror/cdimage/archive/8.0.0-live/amd64/iso-hybrid/debian-live-8.0.0-amd64-standard.iso

and

http://snapshot.debian.org/archive/debian/20150508T155759Z/

**Comment by dpeca** [comment] 2017-06-26 08:13
Thank you.
Now just to find out from which Debian version config files was used for modification, was it exactly 8.0 or newest...

**Comment by dpeca** [comment] 2017-06-26 11:37
Conf files was uploaded on Oct 21, 2015 on github.
So it can be conf files from 8.0, 8.1 and 8.2 - because 8.3 was released in 2016.
We don't know exactly when conf files are modified, only when they were pushed to github.
I guess only @serghey-rodin knows that, because he was probably did modifications.

**Comment by n1trux** [comment] 2017-06-26 12:41
It doesn't really matter if it's 8.0, 8.1 or 8.2 because Debian doesn't change defaults. So you should be fine in using the newest 8.x version to diff it with if your goal is to find out what to modify for 9.0.

In fact, I believe you can even diff the 9.0 files with our configs and use these modifications. Although I don't really know why you need this at all since you still have to check everything the installer does step by step, manually.

**Comment by dpeca** [comment] 2017-06-26 13:02
It will be easy if first add modifications that need to be added and the check step-by-step whole installation process and after it all functionality...


OK, I will try with 8.0 conf files to see diff...

**Comment by carp3** [comment] 2017-06-26 16:10
note that php5 removed from Debian 9. only php7 is available. also mysql replaced with mariadb.

**Comment by henri-hulski** [comment] 2017-07-03 11:59
@dpeca Debian 8.0 support was not added immediately when 8.0 was released as there were some problems.
I guess it was added for 8.2.

**Comment by dpeca** [comment] 2017-07-03 12:25
Right now i'm busy with private obligations, so I can not start with this yet.
If someone can be faster than me - he is welcomed - can help us via push request.
I will write here when I start to work on this - and I will update you about progress.

@henri-hulski 
ok, i'll try with 8.2, i guess there is no big difference in .conf files.

**Comment by mehargags** [comment] 2017-08-19 05:28
any words on this dpeca ?

**Comment by dpeca** [comment] 2017-09-07 13:30
I'm still busy :(
But it is still in my TODO list, so I hope I will do that in next 2 months.

If someone can be faster than me - he is welcomed - he can help us via push request.

**Comment by anton-reutov** [comment] 2017-09-11 10:43
I think officialy it will be in 0.9.8-20, if only one of dev team will not do it before

**Comment by dpeca** [comment] 2017-09-16 11:37
Mostly we need php7.
Hint before we make support for Debian9:
php7 can be easily added to existent Debian8 via dotdeb.org repo.

**Comment by elnino79** [comment] 2017-10-16 13:34
dpeca - PHP7 can be easily added. But Debian 9 have HTTPS/2, and this can't be easily added.

**Comment by dpeca** [comment] 2017-10-18 21:21
I have progress here.
I successfully upgraded Debian8 to Debian9 that running VestaCP.
I will write tomorrow about steps how to do it - I will write step by step manual.

**Comment by dpeca** [comment] 2017-10-21 22:22
Here is the manual - https://forum.vestacp.com/viewtopic.php?f=41&t=15452&p=63601
Please give me feedbacks :)

**Comment by anton-reutov** [comment] 2017-10-22 10:11
Its great, i will test it tommorow

**Comment by UksusoFF** [comment] 2017-11-22 11:32
Any news?

**Comment by dpeca** [comment] 2017-11-22 13:45
I'm very busy this autumn, so installer for Debian9 is still pending on my TODO list.
For now you can only upgrade Debian8 to Debian9 by following steps I provided on mentioned forum topic.

**Comment by jekhor** [comment] 2017-11-30 18:14
I installed Vesta to Debian 9 successfully with modified install script (attached) and Debian jessie vesta repos. Vesta-nginx requires libssl1.0.0, which is missing in the stretch, so you need to install it from jessie repos first.

I have tested only one configuration:
bash vst-install-debian.sh --nginx yes --apache yes --phpfpm no --named no --remi no --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota no --exim yes --dovecot no --spamassassin no --clamav no --mysql yes --postgresql yes

[vst-install-debian.sh.gz](https://github.com/serghey-rodin/vesta/files/1518973/vst-install-debian.sh.gz)

**Comment by mehargags** [comment] 2017-12-04 17:31
@jekhor 
**this works very well**... I can confirm as I just installed it successfully.

# install libssl1.0.0 manually 
```
wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb
dpkg -i libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb
```
and it install through right away.

Haven't tested much, will post more results shortly.

**Comment by tererero** [comment] 2017-12-27 23:07
Why would it need to be exactly the libssl1.0.0 version? Stretch has libssl1.0.2 available, would not that count as replacement?

**Comment by mehargags** [comment] 2017-12-28 08:46
@tererero
why not install  libssl1.0.2 manually and try it out ?

**Closed** 2018-01-05 00:30 UTC
Labels: feature request, installer, Solved
