### ISSUE TITLE
LetsEncrypt errors out when attempting to be enabled

### ISSUE THREAD

**Issue by InquisitiveDevelopment** [serghey-rodin/vesta#1252] opened 2017-08-03 03:51 UTC
### Operating System (OS/VERSION):

Ubuntu 16.04 on digital ocean

### VestaCP Version:

0.9.8

### Installed Software (what you got with the installer):

apache, nginx, mysql, iptables + fail2ban

### Steps to Reproduce:

When adding a site and attempting to add the autossl it shows the error message in the Other Notes section.

### Related Issues/Forum Threads:

Found anything that might be related to this? It might help us find the cause.

### Other Notes:

`Error: Fetching http://[domain]/.well-known/acme-challenge/WbY6PDZ07lflN1AJG-zOeeKa54jNhQtRLDNkQRzs_qA: Connection refused`

**Comment by SCelik** [comment] 2017-08-03 07:57
Try to open http://[domain]/.well-known/acme-challenge/WbY6PDZ07lflN1AJG-zOeeKa54jNhQtRLDNkQRzs_qA in a browser and tell us the http error code?

403? if so, check if any .htaccess file blocks connection.

**Comment by szbnwer** [comment] 2017-08-03 13:55
i'm fighting with similar issues, check out #1235, my problem way once that i had a reused ddns with an assigned ipv6 (that's incrrect currently) and acme wanted to look up that, the 2nd issue was resolved by deactivating the nginx hack with those falses in my codes (see the issue), but i still only obtained the cert, but apache not getting it, but error messages gone, so this is the beginning of the harder part... but anyway i've found that i incorrectly repaired that 'perm' to 'per' instead of 'pem' (even if i know what i am doing :D ) - see my issue to get what i'm talking about... so possibly that will help make stuffs done, other solution is what that link says that i included in my issue

your issue can be based on that the nginx conf haxx not working, you can eliminate that, because nothing will be messed elsewhere...

i will tell when i have a final solution, but i have some progress... (i think tomorrow i will continue working on that)

**Comment by anton-reutov** [comment] 2017-09-12 10:49
Please add screenshot with problem

**Comment by anton-reutov** [comment] 2017-09-15 08:23
Write more how we can reproduce this problem.

**Comment by twoup** [comment] 2017-09-15 12:51
This is the same problem as pull request #1236 - it is caused by a typo on line 58 of v-letsencrypt-add-user. Modify the file and change "-inform perm" to "-inform pem". See [Pull request file](https://github.com/serghey-rodin/vesta/pull/1236/files) for the full text to see the problem.

**Comment by jekhor** [comment] 2017-09-16 20:41
I have the same problem with apache default web template:
![vesta web](https://user-images.githubusercontent.com/117467/30515856-91dbf800-9b38-11e7-8241-2855c6d036d3.png)

**Comment by jekhor** [comment] 2017-09-16 21:03
Works for apache-only installation after applying of #1006

**Comment by szbnwer** [comment] 2017-09-17 15:18
that is an error 404 htmp page iirc and it happens because an nginx hack that gives nginx a config to return for the token instead of put a file there... when i eliminated that code this error gone... it was a simple "false && ..." disabling but nothing should be harmed by cleaning that part out from the codebase, just there gonna be cleaner code, a file in the well-known to observe in case of need (also needed a cleanup for not collecting there a s#itload of dirt)...

just search the issues for let's encrypt (possibly i wrote "lets") and my name, there is more info about my journey...

**Closed** 2017-09-17 16:03 UTC
Labels: awaiting information
