### ISSUE TITLE
Extremely slow clamav db download

### ISSUE THREAD

**Issue by andyzasl** [serghey-rodin/vesta#1158] opened 2017-03-30 07:58 UTC
### Operating System (OS/VERSION):

Ubuntu 16.04, but I think issue is about all Ubuntu

### VestaCP Version:

latest

### Installed Software (what you got with the installer):

apache, nginx, mysql

### Steps to Reproduce:

install 

### Other Notes:
A long time ago i noticed that db update with clam is really slow, for now - it taked over 1 hour during installation of vesta. 

I'd like to ask vestacp team, to create a local mirror to speedup install process.

https://www.clamav.net/documents/private-local-mirrors

**Comment by Skamasle** [comment] 2017-03-30 20:51
In my opinion  mirror not solve this issue if vestacp create it because localmirror is just for local servers or some network, if vesta create a mirror in russia and you run it from USA you may get very slow download

So vesta will need create more mirrors, and this need resources, servers, maintaince etc

And yes clamav have some issues and some times go slow.

Clamav recomendations is just for private networks, you can setup your own mirror if you want install clamav in a lot of servers.

In my case in some locations clamav run fine, and orther ones go slow, also depends of day

**Comment by anton-reutov** [comment] 2017-04-27 17:14
I cant reproduce this issue. My installation took 18 minutes

**Comment by dpeca** [comment] 2017-04-27 17:21
I think it depends on datacenter... because clamav servers is probably limiting bandwidth by the network of our servers.
On my virtualbox (at home) it's very fast, about two minutes only, but on Hetzner network it took 15 to 20 minutes.

**Comment by anton-reutov** [comment] 2017-04-27 17:46
I think we can close this issue

**Closed** 2017-04-27 18:03 UTC

**Comment by andyzasl** [comment] 2017-04-28 07:33
Guys, maybe we could just patch config file to add more mirrors? 
I hope there is a lot of mirrors exists, but only few of it included in config now.

**Comment by MatPain** [comment] 2017-09-13 09:26
i have this issue two, on two new vps linux debian 8

**Comment by giacomodeglinnocenti** [comment] 2018-03-26 14:46
Same issue here on OVH network, it's taking hours (and still at 55%),

is there a way to add more mirror o to select a different one before installation?

I can't afford 4-5 hours to install my env in each situation because of clamav.

**Comment by giacomodeglinnocenti** [comment] 2018-03-27 12:15
Update: today i repeated the procedure and it almost done in 20 minutes on the same machine when yesterday took 5 hours. Today I would say a really better performance, so it definitively depends on the mirror performance.
