### ISSUE TITLE
file manager cant save

### ISSUE THREAD

**Issue by chipzidar** [serghey-rodin/vesta#788] opened 2016-07-25 08:38 UTC
fle manager cant save after editing, displays "Error while saving file"
![5434535](https://cloud.githubusercontent.com/assets/20638018/17095259/767f7078-524b-11e6-90df-c7986de9921d.JPG)

**Comment by naumov-socolov** [comment] 2016-07-25 10:44
what permissions does the file have?
I think the problem could be caused by permissions not allowng to write file

**Comment by SysVoid** [comment] 2016-09-08 10:50
Marking as a non-bug because I too believe this is a permission problem with the one server. File manager works fine for me.

**Closed** 2018-01-30 10:35 UTC
Labels: not a bug

**Comment by oquidave** [comment] 2019-07-30 09:00
Surprised why this was marked as "not a bug". Yes it's a permission issue, but what's the solution? Change the very permissions that VestaCP created for particular user?
