### ISSUE TITLE
Vesta v1 Lets Encrypt Does not work

### ISSUE THREAD

**Issue by 53RG1U5** [serghey-rodin/vesta#2076] opened 2021-10-30 10:59 UTC
In new update letsencrypt does not work.

### Operating System (OS/VERSION):
CentOS 7
### VestaCP Version:
v1
### Installed Software (what you got with the installer):
php-fpm, apache, nginx, mysql

**Comment by 53RG1U5** [comment] 2021-10-30 11:27
Help plz

**Comment by 53RG1U5** [comment] 2021-10-30 11:34
when i used in console v-add-letsencrypt-domain admin DOMAIN
i got
Error: Let's Encrypt validation status 400

**Comment by 53RG1U5** [comment] 2021-10-30 11:46
looks like nginx proxy doe snot work or something like that

**Comment by mostafaahnaw** [comment] 2021-10-30 12:29
also the file manager is not working in the new version.

**Comment by 53RG1U5** [comment] 2021-10-30 12:31
> also the file manager is not working in the new version.

Use FTP but for letsencrypt there is no alternatives

**Comment by anton-reutov** [comment] 2021-10-30 13:05
> 
> 
> also the file manager is not working in the new version.

write more

**Comment by 53RG1U5** [comment] 2021-10-30 13:06
> > also the file manager is not working in the new version.
> 
> write more

What about letsencrypt?

**Comment by anton-reutov** [comment] 2021-10-30 13:07
W

> 
> 
> > > also the file manager is not working in the new version.
> > 
> > 
> > write more
> 
> What about letsencrypt?

we are check this

**Comment by mostafaahnaw** [comment] 2021-10-30 13:50
also in ip:8083/edit/web?domain=domain.com

if you made any changes it give you a message of "Changes have been saved". but all the changes are lost plus you lose all the previous changes

**Comment by mostafaahnaw** [comment] 2021-10-30 13:51
> > also the file manager is not working in the new version.
> 
> write more

i can't copy or upload files

**Comment by 53RG1005** [comment] 2021-10-30 13:52
> also in ip:8083/edit/web?domain=domain.com
> 
> if you made any changes it give you a message of "Changes have been saved". but all the changes are lost plus you lose all the previous changes

same

**Comment by jaapmarcus** [comment] 2021-10-30 14:00
Add new alias adds a new DNS domain but not update the ALIAS

**Comment by mix5003** [comment] 2021-10-30 14:11
many field in Edit Domain use incorrect property for now i create pull request to fixed it #2078

but for letsencrypt issue i still don't known what happend

**Comment by mix5003** [comment] 2021-10-30 14:23
after i dig in to code i think this should been fixed  by #2078

i think root cause is `proxy_template` is not save correctly, so it not create nginx config to response ACME correctly.

if you want a quick fix for letsencrypt type to do this
1. edit `v-change-web-domain-proxy-tpl` at line 45 change '$PROXY' to 'PROXY' (like (this)[https://github.com/serghey-rodin/vesta/pull/2078/files#diff-4f4c6696030bea0e2faf806d813548940f1c67e8031c2a0edac13ce7efe4e0d7]
2. force create proxy config by `v-change-web-domain-proxy-tpl user domain`
3. issue letsencrypt cert by `v-add-letsencrypt-domain user domain`

**Comment by AyhanDelican** [comment] 2021-10-31 17:40
same error on Debian

**Comment by anton-reutov** [comment] 2021-10-31 17:44
Please, waiting, when the new version with most of bug-fixes will be released

**Comment by marchino321** [comment] 2021-11-08 20:08
for me same error

**Comment by marchino321** [comment] 2021-11-08 20:10
> after i dig in to code i think this should been fixed by #2078
> 
> i think root cause is `proxy_template` is not save correctly, so it not create nginx config to response ACME correctly.
> 
> if you want a quick fix for letsencrypt type to do this
> 
> 1. edit `v-change-web-domain-proxy-tpl` at line 45 change '$PROXY' to 'PROXY' (like (this)[https://github.com/[Fix Edit Web page error #2078](https://github.com/serghey-rodin/vesta/pull/2078)/files#diff-4f4c6696030bea0e2faf806d813548940f1c67e8031c2a0edac13ce7efe4e0d7]
> 2. force create proxy config by `v-change-web-domain-proxy-tpl user domain`
> 3. issue letsencrypt cert by `v-add-letsencrypt-domain user domain`

not working i got always same error
![Schermata 2021-11-08 alle 9 10 13 PM](https://user-images.githubusercontent.com/39125194/140810912-e0d64513-179b-441b-85be-ab4fa3880c48.png)
t

**Comment by mix5003** [comment] 2021-11-08 20:21
@marchino321 i think vesta 1.0.0-4 should fixed this. you should try update vestacp and try again

if not success try this
1. run `v-change-web-domain-proxy-tpl user domain default`. eg `v-change-web-domain-proxy-tpl admin example.com default`
2. run `v-add-letsencrypt-domain user domain`. eg `v-add-letsencrypt-domain admin example.com`

**Comment by marchino321** [comment] 2021-11-08 20:39
@mix5003 i'll try to update vastavo but have syntax error have "fi" not "if"
![Schermata 2021-11-08 alle 9 38 38 PM](https://user-images.githubusercontent.com/39125194/140814743-f2e42a50-05b7-4cf6-8040-3edd61849b6d.png)

**Comment by mix5003** [comment] 2021-11-08 20:42
@marchino321  edit that file in line 41. change `fi` to `if` like this
https://github.com/serghey-rodin/vesta/pull/2074/files

**Comment by marchino321** [comment] 2021-11-08 20:54
@mix5003 perfect ty

**Closed** 2021-11-15 22:40 UTC
Labels: Solved
