### ISSUE TITLE
The occupied space is indicated incorrectly on the user on header...

### ISSUE THREAD

**Issue by skorpions2000** [serghey-rodin/vesta#2099] opened 2021-10-31 14:06 UTC
### Operating System (OS/VERSION):

Debian 9.13

### VestaCP Version:

Version: 1.0.0 (Amd64) Release: 2

### Installed Software (what you got with the installer):

vesta(Core Package)
vesta-php(Php Interpreter)
vesta-nginx(Internal Web Server)
vesta-ioncube(Php Encoder)
vesta-softaculous(App Installer)

### Bug?/Problem:

The occupied space is indicated incorrectly on the user. The header indicates that the space is occupied in bytes, but in fact should be indicated in megabytes...?
![06](https://user-images.githubusercontent.com/11683786/139587619-76617f6d-92f8-4314-ad81-4456ce53483f.jpg)

**Comment by anton-reutov** [comment] 2021-10-31 14:11
Try to run this command
sudo /usr/local/vesta/bin/v-update-sys-queue disk
on centos can't reproduce.
i try to reproduce on debian

**Comment by skorpions2000** [comment] 2021-10-31 14:25
Problem no with queue disk, only witch interface... Command working but no fix problem after typing command.
On header shows a value 1/1000 less...
For example, another user has in gigabytes:
![08](https://user-images.githubusercontent.com/11683786/139588103-215611f1-ee85-402c-965e-1cfdaf6763df.jpg)

**Comment by anton-reutov** [comment] 2021-10-31 14:34
Thank you, we will fix this

**Comment by anton-reutov** [comment] 2021-11-03 20:38
Will be in new hot fix release

**Closed** 2021-11-23 08:47 UTC
Labels: bug, confirmed, Solved
