### ISSUE TITLE
All VestaCP is broken , Menu not save, SSL not work, Change Proxy not work

### ISSUE THREAD

**Issue by Penguinehis** [serghey-rodin/vesta#2082] opened 2021-10-30 17:13 UTC
### Operating System (OS/VERSION):

Ubuntu 18.04

![image](https://user-images.githubusercontent.com/54519344/139542916-9d29bb82-49db-415a-b5ca-e77263c476a7.png)

### VestaCP Version:

Release 1.0.0-1

### Installed Software (what you got with the installer):

Default

### Steps to Reproduce:

 v-add-letsencrypt-domain user domain
 Not save the correct SSL and not allow to acess the website

Not working change the proxy template
Not working the Lests encrypt buttom
the command  v-add-letsencrypt-domain broke the domain and not allow to change the SSL
![Untitled](https://user-images.githubusercontent.com/54519344/139542560-b9d1dace-0c0b-4cac-951e-ecd86d574b23.png)
![image](https://user-images.githubusercontent.com/54519344/139542562-e15b8f95-b51a-4172-8aa0-1f69e831ef2b.png)
![Untitled2](https://user-images.githubusercontent.com/54519344/139542573-82fce645-4205-4a6a-b07a-c5a97bc08c1c.png)

Now all my company is broken :/

**Comment by Penguinehis** [comment] 2021-10-30 17:14
![image](https://user-images.githubusercontent.com/54519344/139542634-f3eb1759-655f-47ba-9e88-471bb50c27e4.png)

**Comment by Penguinehis** [comment] 2021-10-30 17:15
This domain has ssl after i updated the SSL certificate with the command broken 

![image](https://user-images.githubusercontent.com/54519344/139542675-7285cb3f-4ca6-4f6e-b811-ff23419378c6.png)

**Comment by Penguinehis** [comment] 2021-10-30 17:16
![image](https://user-images.githubusercontent.com/54519344/139542697-7afe7c64-da1e-4c04-9704-afd31fff0f88.png)

**Comment by anthonyrossbach** [comment] 2021-10-30 17:19
Ubuntu 20 has never been supported.

![86245EC2-ED1C-4D3F-9774-149BA942FA46](https://user-images.githubusercontent.com/5204371/139542801-6a314324-54ad-4848-8dd9-df91760127d4.jpeg)

**Comment by anton-reutov** [comment] 2021-10-30 17:20
Yes, we know. We are working under fixes now.

**Comment by Penguinehis** [comment] 2021-10-30 17:20
Its not 20 sorry

![image](https://user-images.githubusercontent.com/54519344/139542879-6400dd9a-07cb-479e-a531-7103225100ac.png)

**Comment by Penguinehis** [comment] 2021-10-30 17:21
Its 18.04 

i mismatch my dedicated servers

**Comment by Penguinehis** [comment] 2021-10-30 17:21
> Ubuntu 20 has never been supported.
> 
> ![86245EC2-ED1C-4D3F-9774-149BA942FA46](https://user-images.githubusercontent.com/5204371/139542801-6a314324-54ad-4848-8dd9-df91760127d4.jpeg)

Sorry I ended up confusing my dedicated version is 18.04

**Comment by anthonyrossbach** [comment] 2021-10-30 17:22
> > Ubuntu 20 has never been supported.
> > ![86245EC2-ED1C-4D3F-9774-149BA942FA46](https://user-images.githubusercontent.com/5204371/139542801-6a314324-54ad-4848-8dd9-df91760127d4.jpeg)
> 
> Sorry I ended up confusing my dedicated version is 18.04

All good it happens.

**Comment by anthonyrossbach** [comment] 2021-10-30 17:23
I know the fix for this one second I am looking up the path names.

**Comment by Penguinehis** [comment] 2021-10-30 17:23
> > > Ubuntu 20 has never been supported.
> > > ![86245EC2-ED1C-4D3F-9774-149BA942FA46](https://user-images.githubusercontent.com/5204371/139542801-6a314324-54ad-4848-8dd9-df91760127d4.jpeg)
> > 
> > 
> > Sorry I ended up confusing my dedicated version is 18.04
> 
> All good it happens.

yes for me it is even common , I ended up confusing it because this server only access its terminal when something really bad happens haha

**Comment by Penguinehis** [comment] 2021-10-30 17:24
but at least the essential thing is my emails , and DNS are working perfectly

**Comment by anthonyrossbach** [comment] 2021-10-30 17:26
First turn OFF SSL on the site by removing the checkbox.

Go to this path: `/usr/local/vesta/data/users` and open the user folder for this site and open web.conf and turn `LETSENCRYPT='yes'` and set to no and save. Now you can regenerate a certificate.

This is caused by the system thinking the cert is in place so it never creates the files and just tries to update them.

**Comment by Penguinehis** [comment] 2021-10-30 17:27
> First turn OFF SSL on the site by removing the checkbox.
> 
> Go to this path: `/usr/local/vesta/data/users` and open the user folder for this site and open web.conf and edit `LETSENCRYPT='yes'` and set to no and save. Now you can regenerate a certificate.
> 
> This is caused by the system thinking the cert is in place so it never creates the files and just tries to update them.

in this case I tested it with a new site that I generated now , and I had the same problem

**Comment by Penguinehis** [comment] 2021-10-30 17:28
I gonna record a video for show

**Comment by anthonyrossbach** [comment] 2021-10-30 17:29
Oh. Strange, did you reboot to clear the temp folder also?

I have seen this error before related to that check never getting set to no and this is usually my fix.

But if it happens on a new site I am unsure. I would still check that the web.conf file is correct due to it having blank info in some of the boxes.

**Comment by Penguinehis** [comment] 2021-10-30 17:35
I'm tryng to show but the lets encrypt hate me haha

![image](https://user-images.githubusercontent.com/54519344/139543309-feacf942-9324-4a05-a43b-35c0208bf1d0.png)

**Comment by ScIT-Raphael** [comment] 2021-10-30 17:36
The error is probaly due to an issue with the proxy-template function, there isnt anything you can do right now - the related LE cerification part will not get loaded which itself leads into an LE400 error. You probaly need to wait for a fix or use an alternative to vesta.

**Comment by Penguinehis** [comment] 2021-10-30 17:37
> The error is probaly due to an issue with the proxy-template function, there isnt anything you can do right now - the related LE cerification part will not get loaded which itself leads into an LE400 error. You probaly need to wait for a fix or use an alternative to vesta.

yes , and when I can put the certificate it gives the error of the prints, as if it didn't exist

**Comment by Penguinehis** [comment] 2021-10-30 17:39
and about changing the vest temporarily, i can't that would lead to access failure for more than 40,000 users who use my API in some indies games that host the data

**Comment by Penguinehis** [comment] 2021-10-31 03:15
Still not solved 

![image](https://user-images.githubusercontent.com/54519344/139565619-aa16dc98-ad6d-48da-b4ce-9e9898e51f2c.png)

![image](https://user-images.githubusercontent.com/54519344/139565624-1731a952-0450-4cd3-bc9b-5ce04b018958.png)

![image](https://user-images.githubusercontent.com/54519344/139565626-47ddb533-fefe-4c72-9b78-5abe54349516.png)

**Comment by jonnydo** [comment] 2021-10-31 08:23
![screencapture-45-147-177-228-8083-edit-web-2021-10-31-11_21_28](https://user-images.githubusercontent.com/40856635/139574348-a207754c-b720-4dd3-93c7-f1e53d1477fa.png)

Настройка домена слетают после сохранения.
Переустановили сервер целиком, проблема осталась.

Причем странно, есть 15 идентичных серверов, а отвалился только один их них.

**Comment by anton-reutov** [comment] 2021-10-31 09:44
> 
> 
> Still not solved
> 
> ![image](https://user-images.githubusercontent.com/54519344/139565619-aa16dc98-ad6d-48da-b4ce-9e9898e51f2c.png)
> 
> ![image](https://user-images.githubusercontent.com/54519344/139565624-1731a952-0450-4cd3-bc9b-5ce04b018958.png)
> 
> ![image](https://user-images.githubusercontent.com/54519344/139565626-47ddb533-fefe-4c72-9b78-5abe54349516.png)

We solve this, but not released yet

**Comment by anton-reutov** [comment] 2021-10-31 09:45
> 
> 
> ![screencapture-45-147-177-228-8083-edit-web-2021-10-31-11_21_28](https://user-images.githubusercontent.com/40856635/139574348-a207754c-b720-4dd3-93c7-f1e53d1477fa.png)
> 
> Настройка домена слетают после сохранения. Переустановили сервер целиком, проблема осталась.
> 
> Причем странно, есть 15 идентичных серверов, а отвалился только один их них.

Исправлено, но пока ещё не выпушено. Фиксим схожие баги.

**Comment by hardwebCZ** [comment] 2021-10-31 13:39
Same problems....
### Operating System (OS/VERSION):

Type here, e.g. **Ubuntu 18.04 server**

### **VestaCP Version:1.0.0 (amd64)**

Can't restart server via button.
Can't add new domain SSL " Lets encrypt "

ah.....how to downgrade back to old version?? This is buggy version, cron not working.. etc.

![1](https://user-images.githubusercontent.com/93477771/139586340-f544e495-55ec-4f9d-bb0a-97bba3c2846f.png)
![2](https://user-images.githubusercontent.com/93477771/139586342-c3801071-4691-422b-8c19-3164cae9e33a.png)

**Closed** 2021-11-14 17:08 UTC
Labels: Solved
