### ISSUE TITLE
Changing vhost DocumentRoot

### ISSUE THREAD

**Issue by DeeJaVu** [serghey-rodin/vesta#1137] opened 2017-03-14 19:53 UTC
it would be nice to see a feature when we add a new domain
we could change the documentroot of it.. for example for now when we add a `example.com`
it creates a document root for `/home/username/web/example.com/public_html/`

but it would be nice if we could change the path to `/home/username/web/example.com/public_html/public` 

for now we need to edit the `apache2.conf` and `nginx.conf` manually

**Comment by skurudo** [comment] 2017-03-14 19:58
Why you won't use templates for this?

/usr/local/vesta/data/templates/web/

**Comment by DeeJaVu** [comment] 2017-03-14 20:36
huh i did not know that !

**Comment by SysVoid** [comment] 2017-03-14 20:39
Closing. Out of scope for the VestaCP core.

**Closed by SysVoid** 2017-03-14 20:39 UTC

**Comment by DeeJaVu** [comment] 2017-03-14 20:42
kurwa

**Comment by SysVoid** [comment] 2017-03-14 20:46
Why are you throwing around insults? Grow up. Issues aren't permanently closed. If another collaborator disagrees, we can discuss it and reopen it if necessary.

I do not feel that something like this is something to be supported by VestaCP core because the entire point of `public_html` is to work as `public`. Specific frameworks that depend on `public` inside of `public_html` should be independently added, not added for everyone.

**Comment by DeeJaVu** [comment] 2017-03-14 20:49
i asked for a feature request but all you do is closing it.. almost every hosting control panel has this feature built-in, but Thank You i won't use vestap anymore.. good by

**Comment by SysVoid** [comment] 2017-03-14 20:52
I have experience with cPanel. In cPanel you must set the document root from within the domain's config. What other hosting control panels have this?

Again, closing the issue isn't permanent. We can still discuss it. I just don't feel that something like this is supported by us.

**Comment by dpeca** [comment] 2017-03-14 20:55
@DeeJaVu from what country you are coming?

**Comment by DeeJaVu** [comment] 2017-03-14 20:58
@dpeca why does that matter from what country i am ?

**Comment by dpeca** [comment] 2017-03-14 21:02
Because you wrote one very bad and offensive word on some language....

**Comment by anton-reutov** [comment] 2017-03-14 21:02
@DeeJaVu Please don't insult our staff. You comment has been deleted

**Comment by DeeJaVu** [comment] 2017-03-14 21:28
@dpeca i can say that i have russian friends

**Comment by SysVoid** [comment] 2017-03-15 08:52
Going to lock this since clearly the discussion is not constructive right now. If you feel that this should be considered, send us your thoughts to dev@vestacp.com.

Thanks!
