### ISSUE TITLE
Domain settings injection

### ISSUE THREAD

**Issue by phm46** [serghey-rodin/vesta#1309] opened 2017-10-23 20:45 UTC
Hello,
I found that it is possible to add malicious characters into domain configuration. This results in unusable domain administration and I had a hard time finding where it stores data, so I can recover it :)

### Operating System (OS/VERSION):
Debian 8

### VestaCP Version:
IDK where to find version number

### Steps to Reproduce:
- Add domain
- Click edit
- Into alliases enter whatever you want, e.g. Test' (single quote is needed to break it)

This will break application, because it goes right into settings in raw form (it should be validated if it's really domain name). Also it can be used to craft custom settings (yes, I know that almost everything you can change in panel).

It take me some time to find location where it stores this data: `/usr/local/vesta/data/users/admin/web.conf`

BTW, Vesta panel is __AWESOME__

**Comment by noogen** [comment] 2017-11-29 02:06
To answer your question, the conf can be found under: /home/%username%/conf/web

Your issue is duplicate of this one - https://github.com/serghey-rodin/vesta/issues/1324 - I'm just doing some house keeping.

**Closed** 2020-11-08 18:09 UTC
