### ISSUE TITLE
When Clicking on Server / Show:CPU /MEM /NET /DISK the topmenu is almost gone

### ISSUE THREAD

**Issue by hollanddata** [serghey-rodin/vesta#2206] opened 2021-12-07 16:04 UTC
### Operating System (OS/VERSION):

Type here, e.g. CentOS 7

### VestaCP Version:

Core Package Version: 1.0.0 (X86_64) Release: 5

When clicking on Server / Show:CPU /MEM /NET /DISK the topmenu is almost gone.

![2021-12-07 16_56_38-Vesta - SERVER](https://user-images.githubusercontent.com/54579231/145063816-b80f9525-7827-4921-b1bd-ab874311f66b.png)
![2021-12-07 16_51_38-Vesta - SERVER](https://user-images.githubusercontent.com/54579231/145063834-4607aecf-f236-4e5c-9be5-77bca316b42a.png)

**Comment by wojsmol** [comment] 2021-12-07 16:19
This is duplicate of https://github.com/serghey-rodin/vesta/issues/2189.

**Closed** 2021-12-31 16:05 UTC
Labels: Solved
