### ISSUE TITLE
Can't enable Let's Encrypt support when using the force-https template.

### ISSUE THREAD

**Issue by DaniWinter** [serghey-rodin/vesta#979] opened 2016-12-06 09:59 UTC
### Operating System (OS/VERSION):

CentOS 7 

### VestaCP Version:

0.9.8 release 17

### Installed Software (what you got with the installer):

Default packages

### Steps to Reproduce:

Domain > SSL Support > Let's Encrypt Support

### Related Issues/Forum Threads:

No

### Other Notes:

You get the following error: Error: Invalid response from http://DOMAIN.COM/.well-known/acme-challenge/fEJeLFCsS2KVQpAR7EIsmtgg-XuUMeJbUIX68S2l_Uk: \

When using the default nginx template it works just fine.

**Comment by Skamasle** [comment] 2016-12-06 12:32
Is reported here -> https://github.com/serghey-rodin/vesta/issues/966

**Comment by kmark** [comment] 2017-01-19 12:57
I'm not so sure that this is a duplicate of #966 since nginx enabled installs handle the `acme-challenge` stuff differently than Apache-only installs according to `v-check-letsencrypt-domain`. It's unlikely 310a3797052f49044f6060bd3b1936b89f2e87cb would resolve this particular issue.

**Comment by ClickSimply** [comment] 2017-05-11 22:07
Just applied the patch and not seeing a positive result, still experiencing this issue.

I have to move nginx from `https-only` config to the default, disable the certificate, then renew manually in the control panel.

Automatic renewal leads to the error above.

**Closed** 2018-08-08 21:51 UTC
